### ISSUE TITLE
Have no idea how to get in touch with you !

### ISSUE THREAD

**Issue by mmitech** [chaeplin/esp8266_and_linux#1]
I have no idea about how to reach to you except this way, I came across the x11-hash python implementation that you did and I am curious if you would do the scrypt-jane implementation for me (of course for a payment).

please reach to me on the email address that is on my profile.

**Comment by chaeplin** [comment]
@mmitech I am not, sorry.
Anyway check : 
Yac is scrypt-jane based.
https://github.com/Hartland/Stratum-Scrypt-Jane/tree/master/yac_scrypt
https://github.com/Rav3nPL/p2pool-yac/tree/master/yac_scrypt

**Comment by mmitech** [comment]
Understood, thanks.
